[package]
name = "tufted"
version = "0.0.1"
entrypoint = "src/tufted.typ"
authors = ["Vsevolod Shegolev <https://github.com/vsheg>"]
license = "MIT"
description = "Responsive web layout with wide margins, elegant sidenotes, and restrained typography."
repository = "https://github.com/vsheg/tufted"
compiler = "0.14.0"
exclude = ["tests", "docs", "Makefile"]
categories = ["layout", "utility"]
keywords = ["cv", "poster", "document", "academic"]

[template]
path = "template"
entrypoint = "config.typ"
